### ISSUE TITLE
checking duplicates against 84000 data

### ISSUE THREAD

**Issue by eroux** [brunogml/rKTs#13]
This is a question for both Esukhia (@ngawangtrinley) and rKTs (@brunogml):

First, 84000 has `538,538a,539`, while rKTs has `538,539,539a`. Looking at the Tohoku, the situation is a bit messy but I tend to think the rKTs option is quite reasonable... what do you think?

Also, ignoring this issue there are differences in the texts identified as duplicates, as these are duplicates in rKTs but not in 84000:
- [ ] D24, D90
- [ ] D270, D512, D852 (84000 has only D270, D852)
- [ ] D538, D1068
- [ ] D558, D1059a

and finally this one is in 84000 but not in rKTs:
- [ ] D193, D739

What do you think?

**Comment by eroux** [comment]
see also https://github.com/Esukhia/derge-kangyur/issues/9

**Comment by ngawangtrinley** [comment]
I guess the 538,538a,539, vs 538,539,539a is something that can only be decided by looking at the Tohoku catalog since it's their creation. The tibetan catalog clearly differentiates 3 texts there.
