### ISSUE TITLE
indicating parallels

### ISSUE THREAD

**Issue by eroux** [brunogml/rKTs#17]
Looking at the list of parallels sent by John, there seem to be a few types of relations that we could encode between works, at the level of the kernel:
- <translationof>T0XXX</translationof>: translation of the Chinese text that has reference XXX in the Taisho
- <parallel>X</parallel>: the whole text is parallel with the whole text of X in a broad sense: different translation, translation of a different Sanskrit version, etc. (ex: D119, 120, 121)
- <seealso>X<seealso>: any other interesting relationship (ex: D145 - D44-17)

@brunogml what do you think? If you agree I'll make a first pass with the data we currently have

**Comment by brunogml** [comment]
Fine! thanks!

**Comment by eroux** [comment]
ah, I already used the notation you proposed in your email in https://github.com/brunogml/rKTs/commit/c96d6757499d4b4c341b16c52b74fec6192c672b I should have closed this issue. Thanks!
