### ISSUE TITLE
outline image reference issue in W22703

### ISSUE THREAD

**Issue by eroux** [brunogml/rKTs#24]
in volume 90 (I5493) of the Narthang Kangyur W22703, the image correspondence is a bit off (at least at the very end), perhaps because of missing images in the BDRC scans?

moved from https://github.com/buda-base/library-issues/issues/404

@karmagongde if you have more details about where the shift happens in the image number / pagination that will be helpful

**Comment by karmagongde** [comment]
@eroux I checked the image in our collection and there is no any missing folios in W22703, volume 90 (I5493).

I found there are 5 folios which as 2 numbers: such as folio 244/245, 254/255, 258/259, 263/264, and 265/266. 
Example:
![Screen Shot 2021-12-23 at 11 23 29 AM](https://user-images.githubusercontent.com/19337852/147268006-5f7ac2fc-cbbb-47bf-bd1b-b7c824a434f1.png)

**Comment by eroux** [comment]
thanks for spotting it! let's wait perhaps after the holiday season, then either I can do it or @brunogml if he has time.

**Comment by brunogml** [comment]
I corrected the json file linking the paginations to the file numbers

**Comment by eroux** [comment]
thanks! I'll reimport the data this week (I hope)
