### ISSUE TITLE
titles to change in Kernel

### ISSUE THREAD

**Issue by drupchen** [brunogml/rKTs#6]
`D3017` and `D3018` have the same title strings in `tanjurd.xml`.

`D3017`'s title is `ཤི་བའི་སེམས་ཅན་སྡིག་པ་ལས་ཐར་བར་བྱེད་པའི་རོ་སྲེག་པའི་ཆོ་ག་དུག་སྦྱངས་གསལ་བའི་མེ་ལོང` (seen in [074_རྒྱུད་འགྲེལ།_པུ.txt](https://github.com/Esukhia/derge-tengyur/blob/master/derge-tengyur-tags/074_%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%B4%E0%BD%91%E0%BC%8B%E0%BD%A0%E0%BD%82%E0%BE%B2%E0%BD%BA%E0%BD%A3%E0%BC%8D_%E0%BD%94%E0%BD%B4.txt), between `68b.1` and `68b.2`)

**Comment by eroux** [comment]
fixed
